---
apiVersion: v1
kind: Service
metadata:
  name: back-service
  labels:
    app: rps
spec:
  ports:
    - port: 5002
      protocol: TCP
      targetPort: 5002
  selector:
    app: rps
    tier: back
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-service
  labels:
    app: rps
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rps
      tier: back
  template:
    metadata:
      labels:
        app: rps
        tier: back
    spec:
      containers:
        - image: puunsn/back:latest
          name: back-service
          ports:
            - containerPort: 5002
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 10
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 10

