---
apiVersion: v1
kind: Service
metadata:
  name: bot-service
  labels:
    app: rps
spec:
  ports:
    - port: 5003
      protocol: TCP
      targetPort: 5003
  selector:
    app: rps
    tier: bot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-service
  labels:
    app: rps
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rps
      tier: bot
  template:
    metadata:
      labels:
        app: rps
        tier: bot
    spec:
      containers:
        - image: puunsn/bot:latest
          name: bot-service
          ports:
            - containerPort: 5003
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 10
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 10

