---
apiVersion: v1
kind: Service
metadata:
  name: front-service
  labels:
    app: rps
spec:
  type: NodePort
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
      nodePort: 30001
  selector:
    app: rps
    tier: front
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-service
  labels:
    app: rps
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rps
      tier: front
  template:
    metadata:
      labels:
        app: rps
        tier: front
    spec:
      containers:
        - image: puunsn/front:latest
          imagePullPolicy: Always
          name: front-service
          ports:
            - containerPort: 5000
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 10
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 10

